name: CI - On Pull Request

on:
  pull_request:
    branches:
      - "*"

jobs:
  setup:
    name: Testing Application
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "18"
          check-latest: true

      - name: Installing Dependencies
        run: npm install
